# Generated by Django 3.1.12 on 2021-12-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210207_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
